# based on https://github.com/larseggert/homebrew-mytap/blob/master/.travis.yml

language: ruby
matrix:
  include:
    - osx_image: xcode8.3
      os: osx
      rvm: system
    - osx_image: xcode7.3
      os: osx
      rvm: system
    - osx_image: xcode6.4
      os: osx
      rvm: system
    - os: linux
      rvm: system
      services: docker
      sudo: required
  allow_failures:
    - os: linux

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPO="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPO";
      git -C "$HOMEBREW_REPOSITORY" fetch;
      git -C "$HOMEBREW_REPO" reset --hard origin/master;
      git -C "$HOMEBREW_REPO" clean -qxdff;
      mkdir -p "$HOMEBREW_REPO/Library/Taps/larseggert";
      ln -s "$TRAVIS_BUILD_DIR" "$HOMEBREW_REPO/Library/Taps/larseggert/homebrew-mytap";
      cd "$HOMEBREW_REPO/Library/Taps/larseggert/homebrew-mytap";
      export TRAVIS_BUILD_DIR="$HOMEBREW_REPO/Library/Taps/larseggert/homebrew-mytap";
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker pull sjackman/linuxbrew-standalone;
      docker run
        -v $(pwd):/home/linuxbrew/homebrew-mytap
        sjackman/linuxbrew-standalone
        /bin/sh -c 'brew tap homebrew/python && brew update && mkdir -p "$(brew --repo)/Library/Taps/larseggert" && cp -rf ~/homebrew-mytap $(brew --repo)/Library/Taps/larseggert/homebrew-mytap';
      docker commit $(docker ps -l -q) linuxbrew;
    fi
  - env | grep TRAVIS | tee /tmp/travis.env

install:
  - if [ "$HOMEBREW_RUBY" = "1.8.7" ]; then
      brew install homebrew/versions/ruby187;
      export HOMEBREW_RUBY_PATH="/usr/local/opt/ruby187/bin/ruby";
      brew untap homebrew/versions;
    fi
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew test-bot;
    else
      docker run
        -w /home/linuxbrew/.linuxbrew/Library/Taps/larseggert/homebrew-mytap
        --env-file /tmp/travis.env
        -t
        linuxbrew
        brew test-bot --tap=larseggert/homebrew-mytap;
    fi

notifications:
  email:
    on_success: never
    on_failure: always
