language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - git -C $(brew --repo) reset --hard origin/master
  - git -C $(brew --repo) clean -qxdff
  # - brew tap homebrew/dupes
  # - brew tap homebrew/versions
  - brew update
  - ln -s "$TRAVIS_BUILD_DIR" $(brew --repo)/Library/Taps/larseggert/homebrew-mytap
  - cd $(brew --repo)/Library/Taps/larseggert/homebrew-mytap
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/larseggert/homebrew-mytap"
  - env | grep TRAVIS_

script:
  - brew test-bot

notifications:
  email:
    on_success: never
    on_failure: always
